name: Trivy CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  trivy_scan:
    name: Run Trivy Vulnerability Scanner
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v1

    - name: Install and run Trivy
      uses: aquasecurity/trivy-action@0.5.3
      with:
        scan-type: 'fs'
        input: '.'
        format: 'json'
        output: 'trivy-results.json'

    - name: Upload Trivy Scan Results
      uses: actions/upload-artifact@v2
      with:
        name: trivy-results
        path: trivy-results.json
